// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct BubbleSort
{
  struct BubbleSort_vtable *vptr;
};
struct BBS
{
  struct BBS_vtable *vptr;
  int*  number;
  int size;
};
// vtables structures
struct BubbleSort_vtable
{
};

struct BBS_vtable
{
  int (*Start)();
  int (*Sort)();
  int (*Print)();
  int (*Init)();
};


// vtables declared
struct BubbleSort_vtable BubbleSort_vtable_ ;
struct BBS_vtable BBS_vtable_ ;

// methods
int BBS_Start(struct BBS * this, int sz)
{
  int aux01;
  struct BBS * x_1;
  struct BBS * x_2;
  struct BBS * x_3;
  struct BBS * x_4;
  int x_5;
  int x_6;
  int x_7;
  int x_8;

L_0:
  x_5 = this->vptr->Init(this, sz);
  aux01 = x_5;
  x_6 = this->vptr->Print(this);
  aux01 = x_6;
  System_out_println (99999);
  x_7 = this->vptr->Sort(this);
  aux01 = x_7;
  x_8 = this->vptr->Print(this);
  aux01 = x_8;
  return 0;
}
int BBS_Sort(struct BBS * this)
{
  int nt;
  int i;
  int aux02;
  int aux04;
  int aux05;
  int aux06;
  int aux07;
  int j;
  int t;
  int x_9;
  int x_10;
  int x_11;
  int x_12;
  int x_13;
  int x_14;
  int x_15;
  int x_16;
  int x_17;
  int x_18;
  int x_19;
  int x_20;
  int x_21;

L_1:
  x_9 = this->size - 1;
  i = x_9;
  aux02 = -1;
  goto L_2;
L_2:
  x_10 = aux02 < i;
  if (x_10)
    goto L_3;
  else
    goto L_4;
L_3:
  j = 1;
  goto L_5;
L_5:
  x_12 = i + 1;
  x_11 = j < x_12;
  if (x_11)
    goto L_6;
  else
    goto L_7;
L_6:
  x_13 = j - 1;
  aux07 = x_13;
  x_14 = this->number[aux07];
  aux04 = x_14;
  x_15 = this->number[j];
  aux05 = x_15;
  x_16 = aux05 < aux04;
  if (x_16)
    goto L_8;
  else
    goto L_9;
L_9:
  nt = 0;
  goto L_10;
L_8:
  x_17 = j - 1;
  aux06 = x_17;
  x_18 = this->number[aux06];
  t = x_18;
  x_19 = this->number[j];
  this->number[aux06] = x_19;
  this->number[j] = t;

  goto L_10;
L_10:
  x_20 = j + 1;
  j = x_20;

  goto L_5;
L_7:
  x_21 = i - 1;
  i = x_21;

  goto L_2;
L_4:
  return 0;
}
int BBS_Print(struct BBS * this)
{
  int j;
  int x_22;
  int x_23;
  int x_24;

L_11:
  j = 0;
  goto L_12;
L_12:
  x_22 = j < this->size;
  if (x_22)
    goto L_13;
  else
    goto L_14;
L_13:
  x_23 = this->number[j];
  System_out_println (x_23);
  x_24 = j + 1;
  j = x_24;

  goto L_12;
L_14:
  return 0;
}
int BBS_Init(struct BBS * this, int sz)
{
  int*  x_25;

L_15:
  this->size = sz;
  x_25 = (int *)Tiger_new_array(sz);
  this->number = x_25;
  this->number[0] = 20;
  this->number[1] = 7;
  this->number[2] = 12;
  this->number[3] = 18;
  this->number[4] = 2;
  this->number[5] = 11;
  this->number[6] = 6;
  this->number[7] = 9;
  this->number[8] = 19;
  this->number[9] = 5;
  return 0;
}

// vtables
struct BubbleSort_vtable BubbleSort_vtable_ = 
{
};

struct BBS_vtable BBS_vtable_ = 
{
  BBS_Start,
  BBS_Sort,
  BBS_Print,
  BBS_Init,
};


// main method
int Tiger_main ()
{
  struct BBS * x_0;
  int x_26;
  struct BBS * x_27;

L_16:
  x_27 = ((struct BBS*)(Tiger_new (&BBS_vtable_, sizeof(struct BBS))));
  x_26 = x_27->vptr->Start(x_27, 10);
  System_out_println (x_26);
  return 0;
}




void *prev;
