// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct LinearSearch
{
  struct LinearSearch_vtable *vptr;
};
struct LS
{
  struct LS_vtable *vptr;
  int*  number;
  int size;
};
// vtables structures
struct LinearSearch_vtable
{
};

struct LS_vtable
{
  int (*Start)();
  int (*Print)();
  int (*Search)();
  int (*Init)();
};


// vtables declared
struct LinearSearch_vtable LinearSearch_vtable_ ;
struct LS_vtable LS_vtable_ ;

// methods
int LS_Start(struct LS * this, int sz)
{
  int aux01;
  int aux02;
  struct LS * x_1;
  struct LS * x_2;
  struct LS * x_3;
  struct LS * x_4;
  struct LS * x_5;
  struct LS * x_6;
  int x_7;
  int x_8;
  int x_9;
  int x_10;
  int x_11;
  int x_12;

L_0:
  x_7 = this->vptr->Init(this, sz);
  aux01 = x_7;
  x_8 = this->vptr->Print(this);
  aux02 = x_8;
  System_out_println (9999);
  x_9 = this->vptr->Search(this, 8);
  System_out_println (x_9);
  x_10 = this->vptr->Search(this, 12);
  System_out_println (x_10);
  x_11 = this->vptr->Search(this, 17);
  System_out_println (x_11);
  x_12 = this->vptr->Search(this, 50);
  System_out_println (x_12);
  return 55;
}
int LS_Print(struct LS * this)
{
  int j;
  int x_13;
  int x_14;
  int x_15;

L_1:
  j = 1;
  goto L_2;
L_2:
  x_13 = j < this->size;
  if (x_13)
    goto L_3;
  else
    goto L_4;
L_3:
  x_14 = this->number[j];
  System_out_println (x_14);
  x_15 = j + 1;
  j = x_15;

  goto L_2;
L_4:
  return 0;
}
int LS_Search(struct LS * this, int num)
{
  int j;
  int ls01;
  int ifound;
  int aux01;
  int aux02;
  int nt;
  int x_16;
  int x_17;
  int x_18;
  int x_19;
  int x_20;
  int x_21;
  int x_22;

L_5:
  j = 1;
  ls01 = 0;
  ifound = 0;
  goto L_6;
L_6:
  x_16 = j < this->size;
  if (x_16)
    goto L_7;
  else
    goto L_8;
L_7:
  x_17 = this->number[j];
  aux01 = x_17;
  x_18 = num + 1;
  aux02 = x_18;
  x_19 = aux01 < num;
  if (x_19)
    goto L_9;
  else
    goto L_10;
L_10:
  x_21 = aux01 < aux02;
  x_20 = !(x_21);
  if (x_20)
    goto L_12;
  else
    goto L_13;
L_13:
  ls01 = 1;
  ifound = 1;
  j = this->size;

  goto L_14;
L_12:
  nt = 0;
  goto L_14;
L_14:
  goto L_11;
L_9:
  nt = 0;
  goto L_11;
L_11:
  x_22 = j + 1;
  j = x_22;

  goto L_6;
L_8:
  return ifound;
}
int LS_Init(struct LS * this, int sz)
{
  int j;
  int k;
  int aux01;
  int aux02;
  int*  x_23;
  int x_24;
  int x_25;
  int x_26;
  int x_27;
  int x_28;
  int x_29;
  int x_30;

L_15:
  this->size = sz;
  x_23 = (int *)Tiger_new_array(sz);
  this->number = x_23;
  j = 1;
  x_24 = this->size + 1;
  k = x_24;
  goto L_16;
L_16:
  x_25 = j < this->size;
  if (x_25)
    goto L_17;
  else
    goto L_18;
L_17:
  x_26 = 2 * j;
  aux01 = x_26;
  x_27 = k - 3;
  aux02 = x_27;
  x_28 = aux01 + aux02;
  this->number[j] = x_28;
  x_29 = j + 1;
  j = x_29;
  x_30 = k - 1;
  k = x_30;

  goto L_16;
L_18:
  return 0;
}

// vtables
struct LinearSearch_vtable LinearSearch_vtable_ = 
{
};

struct LS_vtable LS_vtable_ = 
{
  LS_Start,
  LS_Print,
  LS_Search,
  LS_Init,
};


// main method
int Tiger_main ()
{
  struct LS * x_0;
  int x_31;
  struct LS * x_32;

L_19:
  x_32 = ((struct LS*)(Tiger_new (&LS_vtable_, sizeof(struct LS))));
  x_31 = x_32->vptr->Start(x_32, 10);
  System_out_println (x_31);
  return 0;
}




void *prev;
