// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// Control-flow Graph

// structures
struct Sum
{
  struct Sum_vtable *vptr;
};
struct Doit
{
  struct Doit_vtable *vptr;
};
// vtables structures
struct Sum_vtable
{
};

struct Doit_vtable
{
  int (*doit)();
};


// vtables declared
struct Sum_vtable Sum_vtable_ ;
struct Doit_vtable Doit_vtable_ ;

// methods
int Doit_doit(struct Doit * this, int n)
{
  int sum;
  int i;
  int x_1;
  int x_2;
  int x_3;

L_0:
  i = 0;
  sum = 0;
  goto L_1;
L_1:
  x_1 = i < n;
  if (x_1)
    goto L_2;
  else
    goto L_3;
L_2:
  x_2 = sum + i;
  sum = x_2;
  x_3 = i + 1;
  i = x_3;

  goto L_1;
L_3:
  return sum;
}

// vtables
struct Sum_vtable Sum_vtable_ = 
{
};

struct Doit_vtable Doit_vtable_ = 
{
  Doit_doit,
};


// main method
int Tiger_main ()
{
  struct Doit * x_0;
  int x_4;
  struct Doit * x_5;

L_4:
  x_5 = ((struct Doit*)(Tiger_new (&Doit_vtable_, sizeof(struct Doit))));
  x_4 = x_5->vptr->doit(x_5, 20);
  System_out_println (x_4);
  return 0;
}




void *prev;
